### ISSUE TITLE
Main Branch Outdated?

### ISSUE THREAD

**Issue by dangoh123** [astro-group-bristol/AccretionFormulae.jl#15]
I've been trying to merge my version of the code with the main branch (I think that's the right terminology, referring to [this](https://github.com/astro-group-bristol/AccretionFormulae.jl)), and when I tried to, GitHub told me to make a pull request on my fork, and checkout using the command line:
![Capture2](https://user-images.githubusercontent.com/94124028/155759443-8bd8a8ec-03c9-44c0-a52a-9ee44a96f3b8.PNG)

Following those instructions gave me the following error at the end:

```
PS C:\Users\Dan\Documents\Uni\Year 4\Project\GitHub\DevEnv\dev\AccretionFormulae> git push origin main
remote: Permission to astro-group-bristol/AccretionFormulae.jl.git denied to dangoh123.
fatal: unable to access 'https://github.com/astro-group-bristol/AccretionFormulae.jl/': The requested URL returned error: 403
```

It also replaced the code I have with an old version of the code (the square root is still wrong in the `r_isco` function, which was fixed on Monday or Tuesday). Fortunately I backed up what I had, but I'm not too sure where the main branch is meant to be at the moment.

**Comment by fjebaker** [comment]
The key here is
```
Permission to astro-group-bristol/AccretionFormulae.jl.git denied to dangoh123.
```
You're trying to push to _this repository_, not your fork. It could be the remotes are incorrect; to update that, use
```
git remote set-url origin "https://github.com/dangoh123/AccretionFormulae.jl"
```
and try your push again.

If it was that, then this was probably something we did on Wednesday, and I must have forgotten to undo it. If that doesn't fix it, or something more catastrophic happens, I would recommend just deleting your fork and re-forking (a standard practice :p).

Let me know how it goes!

**Comment by dangoh123** [comment]
I ran that, and it seemed to work fine, cheers.
