### ISSUE TITLE
Line profiles

### ISSUE THREAD

**Issue by phajy** [astro-group-bristol/AccretionFormulae.jl#23]
It would be good to be able to calculate simple line profiles from the disk images. We should be able to create a histogram that shows the line profile. Here is some pseudo-code that should do that.

```
loop over x in image
  loop over y in image
    g = calculated redshift in pixel (x, y) # g = frequency observed / frequency emitted
    ix = calculate some index in the array used for the histogram
    flux = calculated emitted flux in pixel (x, y) # in some arbitrary units - this is OK if we just want the line shape
    line_profile [ix] += flux * g^4 # I think g^4 takes into account all of the relativistic effects for a delta-function line
```

This should produce a nice line profile!

**Comment by fjebaker** [comment]
@phajy Line profiles are, from what I've seen, binned against observed energy E. So

> `ix = calculate some index in the array used for the histogram`

would be some index for `E + dE` right?

In which case, implementing this is very straight forward, and we can use the binning algorithms in Plots.jl by passing a vector of line profile values and corresponding E.

**Comment by phajy** [comment]
Yes, that would be counts in a bin from `E` to `E + dE`.

**Comment by phajy** [comment]
@fjebaker @dangoh123 @kyle8mcknight : One thing I wanted to mention about the line profile calculation draft was that I changed the size to have the same x and y dimensions with square pixels.

**Comment by dangoh123** [comment]
I think that should be fine anyway, as we had already done something similar, and the aspect ratio shouldn't affect the line profile, as it should just be for the output image, not the matrix we are analysing.

**Comment by fjebaker** [comment]
Line profile example script in #26, closing this for now.
